ALTER TABLE sites ADD COLUMN IF NOT EXISTS edition_enabled BOOLEAN DEFAULT false;

CREATE TABLE IF NOT EXISTS editions (
	   id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	   site_id INT NOT NULL REFERENCES sites(id) ON DELETE RESTRICT,
	   number INT NOT NULL,
	   date TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS edition_posts (
	   edition_id INT NOT NULL REFERENCES editions(id) ON DELETE RESTRICT,
	   post_id INT NOT NULL REFERENCES posts(id) ON DELETE RESTRICT,
	   PRIMARY KEY(edition_id, post_id)
);
