[package]
name = "blog_cgi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "admin"
path = "src/main.rs"

[[bin]]
name = "migrations"
path = "src/migrate.rs"

[[bin]]
name = "blog"
path = "src/public.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
askama = { version = "0.12.0", features = ["markdown"] }
async-std = "1.12.0"
bcrypt = "0.14.0"
cgi = "0.6.0"
http = "0.2.9"
itertools = "0.10.5"
ordinal = "0.3.2"
regex = "1.8.1"
serde = { version = "1.0.159", features = ["derive"] }
serde-querystring = "0.2.1"
serde_json = "1.0.95"
sqlx = { version = "0.6.3", features = ["postgres", "runtime-async-std-rustls", "json", "uuid", "time", "migrate"] }
time = { version = "0.3.20", features = ["serde", "parsing", "formatting"] }
uuid = { version = "1.3.1", features = ["v4"] }

[profile.release]
opt-level = 3       # Optimize for size
lto = 'thin'
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
