[package]
name = "atproto"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
tokio = { workspace = true }
bsky-sdk = "0.1.20"
atrium-api = "0.25.4"

anyhow = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true  }